ifeq ($(CONFIG_PLATFORM_ANDROID_INTEL_X86), y)
ccflags-y += -DCONFIG_PLATFORM_ANDROID_INTEL_X86
ccflags-y += -DCONFIG_PLATFORM_INTEL_BYT
ccflags-y += -DCONFIG_LITTLE_ENDIAN -DCONFIG_PLATFORM_ANDROID
ccflags-y += -DCONFIG_CONCURRENT_MODE
ccflags-y += -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT
ccflags-y += -DCONFIG_SKIP_SIGNAL_SCALE_MAPPING
ifeq ($(CONFIG_SDIO_HCI), y)
ccflags-y += -DCONFIG_RESUME_IN_WORKQUEUE
endif
endif
